version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - app/backend/.env
    volumes:
      - ./app/backend:/app

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./app/frontend:/app
    depends_on:
      - backend
