apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: rafcetario
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: fargate-sa
      containers:
        - name: backend
          image: 376129848196.dkr.ecr.eu-west-1.amazonaws.com/rafcetario-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: database_url
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: aws_secret_access_key
      nodeSelector:
        kubernetes.io/os: linux
