apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: rafcetario
spec:
  type: NodePort  
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
