name: CD - Build & Push Backend Docker Image to AWS ECR

on:
  workflow_run:
    workflows: ["CI - Testing & Linting"]
    types:
      - completed
    conclusions:
      - success  

jobs:
  build-and-push:
    name: Construir y subir imagen del backend a ECR
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1  

      - name: Iniciar sesión en AWS ECR
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

      - name: Construir y etiquetar imagen del backend
        run: |
          docker build \
          --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
          -f docker/backend/Dockerfile \
          -t rafcetario-backend:latest \
          -t ${{ secrets.AWS_ECR_REGISTRY }}/rafcetario-backend:${{ github.sha }} \
          -t ${{ secrets.AWS_ECR_REGISTRY }}/rafcetario-backend:latest \
          .

      - name: Subir imágenes a AWS ECR
        run: |
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/rafcetario-backend:${{ github.sha }}
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/rafcetario-backend:latest
